Redirect desktop client when 426 response is received
nextcloud/spreed pull request #10156
Opened 2023-08-09 12:59 UTC by Antreesy

### ☑️ Resolves

* Fix nextcloud/talk-desktop#209
* Fix #9660 
* Wording is aligned with mobile clients

### 🖼️ Screenshots

| 🏡 After |
|---|
| ![image](https://github.com/nextcloud/spreed/assets/93392545/bf57e953-7c7f-47f3-b20b-98ccee3a50d1) |

### 🚧 Tasks

- [ ] Visual check
- [ ] Code review

To test: adjust constant to be higher than current Talk Desktop version (0.9.0):

https://github.com/nextcloud/spreed/blob/67c22f97d7d9a10fe085f7bc65ee4f0c23c9e652/lib/Middleware/CanUseTalkMiddleware.php#L53

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

2023-08-09 14:04 UTC, ShGKme requested changes
I understand that the solution in this PR implements approach used for the talk hash invalidation. But I'd prefer to have a different approach here and refactor talk hash later.

cc @danxuliu for a second opinion here

---

I'm not sure it should be done in the Talk web frontend in general. It's a large part that is not relevant for the web frontend.

We can do it directly in the desktop client:
1. Check for the status in the http response (any response)
  - Simple way - add interceptor directly in the place, where we need to react on it. Aka in some root component add `axios.interceptors.response.use`
  - Better in my opinion way in my opinion - add 426 response handler in the http client to avoid http client abstraction leak here
- Add a new route with new view by [addRoute](https://router.vuejs.org/api/interfaces/Router.html#addRoute)
- Show the message in the desktop frontend and make the same redirect as in this PR

2023-08-09 17:47 UTC, nickvergessen commented on src/views/UpgradeRequiredView.vue
> +		<h2>{{ t('spreed', 'The app is too old and no longer supported by this server.') }}</h2>
```suggestion
		<h2>{{ t('spreed', 'The client version is too old and no longer supported by this server.') }}</h2>
```

2023-08-09 17:47 UTC, nickvergessen commented on src/store/talkHashStore.js
> +			context.commit('setUpgradeWarningToast', showError(t('spreed', 'The app is too old and no longer supported by this server. Update is required.'), {
```suggestion
			context.commit('setUpgradeWarningToast', showError(t('spreed', 'The client version is too old and no longer supported by this server. Update is required.'), {
```

2023-08-10 15:35 UTC, closed without merging

2023-08-10 15:35 UTC, Antreesy commented
Closed in favor of https://github.com/nextcloud/talk-desktop/pull/289

2023-08-10 16:59 UTC, danxuliu commented
> I understand that the solution in this PR implements approach used for the talk hash invalidation. But I'd prefer to have a different approach here and refactor talk hash later.
> 
> cc @danxuliu for a second opinion here

I am late to the party... but I fully agree :-)