perf(dashboard): implement widget item api v2
nextcloud/spreed pull request #10250
Opened 2023-08-17 13:33 UTC by st3iny

### ☑️ Resolves

* Ref https://github.com/nextcloud/server/pull/39937

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not required
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [ ] 🔖 Capability is added or not needed

2023-08-18 11:40 UTC, nickvergessen requested changes

2023-08-18 11:40 UTC, nickvergessen commented on lib/Dashboard/TalkWidget.php
> +			$this->l10n->t('More talk rooms')
```suggestion
			$this->l10n->t('More conversations')
```

2023-08-18 13:42 UTC, nickvergessen commented on lib/Dashboard/TalkWidget.php
> +use OCP\Dashboard\IAPIWidgetV2;
```suggestion
```

2023-08-18 13:42 UTC, nickvergessen commented on lib/Dashboard/TalkWidget.php
> +class TalkWidget implements IAPIWidget, IAPIWidgetV2, IIconWidget, IButtonWidget, IOptionWidget, IConditionalWidget, IReloadableWidget {
```suggestion
class TalkWidget implements IAPIWidget, IIconWidget, IButtonWidget, IOptionWidget, IConditionalWidget, IReloadableWidget {
```

2023-08-18 13:43 UTC, st3iny commented on lib/Dashboard/TalkWidget.php
> +			$this->l10n->t('More talk rooms')
Done

2023-08-18 13:44 UTC, nickvergessen commented on lib/Dashboard/TalkWidget.php
> +		$allRooms = $this->manager->getRoomsForUser($userId, $sessionIds, true);
You are actually not using the sessions, so we can also skip fetching them.

```suggestion
		$allRooms = $this->manager->getRoomsForUser($userId, [], true);
```

2023-08-18 18:04 UTC, st3iny commented on lib/Dashboard/TalkWidget.php
> +		protected TalkSession $session,
```suggestion
```

2023-08-22 14:42 UTC, nickvergessen commented
Arg, same problem with the search and smart picker now applies: #9867

2024-04-09 09:18 UTC, nickvergessen approved these changes

2024-04-10 07:41 UTC, nickvergessen approved these changes

2024-04-10 07:41 UTC, nickvergessen commented
/backport to stable29

2024-04-10 07:56 UTC, merged