fix(NewMessage, EditabeTextField) - don't parse NcRichContenteditable output before sending
nextcloud/spreed pull request #10422
Opened 2023-08-30 12:42 UTC by Antreesy

### ☑️ Resolves

* Fix #10227
* Fix #10412
* Now Talk doesn't make additional parsing, only the one provided by NcRichContenteditable

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
![image](https://github.com/nextcloud/spreed/assets/93392545/d9b29f03-f125-4671-97b1-a4020842edae) | ![image](https://github.com/nextcloud/spreed/assets/93392545/f2dedad1-50ba-464b-acee-d1e9649cd565)
![image](https://github.com/nextcloud/spreed/assets/93392545/3dbb674b-43ef-4e91-8f7d-bdf9303bb265) | ![image](https://github.com/nextcloud/spreed/assets/93392545/c2921f6c-7a9e-42ca-8afb-dfeae82fbd5b)

### 🚧 Tasks

- [ ] Follow-ups :warning: 
  - [ ] Special symbols inside of code blocks are not parsed
  - [ ] Pasted (provided) special symbols inside of NcRichContenteditable are not parsed
  - [ ] Description is not parsed (`'@nextcloud/vue/dist/Mixins/richEditor.js'`)
  ![image](https://github.com/nextcloud/spreed/assets/93392545/03022f9c-2230-4d4d-8001-56c6b6afcc04)

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required (should be tested upstream)
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

2023-08-30 12:48 UTC, nickvergessen commented on src/store/messagesStore.js
> +		context.dispatch('addTemporaryMessage', temporaryMessage)
Does it behave correctly for broadcasted messages in breakout rooms?

2023-08-31 12:14 UTC, DorraJaouad requested changes
It seems like an issue with text storing in NcRichContenteditable ?
https://github.com/nextcloud/spreed/assets/84044328/4c82418c-6b6d-48f3-8d48-89ce636b915c

2023-08-31 12:20 UTC, Antreesy commented
> It seems like an issue with text storing in NcRichContenteditable ?

Yes, that's how the component gives away the output, it escapes all special symbols for security reasons

2023-08-31 12:42 UTC, Antreesy commented
P.S. updated PR, add parsing of special symbols to the "Copy formatted message" as example

Either we:
 - do the same for description, leftSidebar, quotes, etc wherever we can get an output of NcRichContenteditable
 - or fix upstream issue https://github.com/nextcloud-libraries/nextcloud-vue/issues/4492, and don't escape special symbols, but that requires more expertise as it could make some security breaches

2023-08-31 14:12 UTC, Antreesy commented
P.S. updated PR, raised and referenced an upstream issue

2023-08-31 17:08 UTC, nickvergessen approved these changes
Seems to work

2023-08-31 17:10 UTC, merged

2023-08-31 17:10 UTC, nickvergessen commented
/backport to stable27