Add presenter overlay when sharing screen
nextcloud/spreed pull request #10669
Opened 2023-10-09 21:16 UTC by DorraJaouad

### ☑️ Resolves

* Fix #4478
* The presenter overlay is removed when stripe is open because the video is there anyway.
* You can hide and unhide by clicking on the presenter overlay
* When hidden, a button will be shown.

## 🖌️ UI Checklist

### 🖼️ Screenshots / Screencasts

| 🏚️ Default | 🏡 On hover |  🏡 Clicked | 🏡 Stripe Open |
|------------|----------|----------|----------|
| ![Presenter1](https://github.com/nextcloud/spreed/assets/84044328/646e561f-b3ae-4811-95c5-506f7b7c86f4)      | ![Screenshot 2023-10-09 230236](https://github.com/nextcloud/spreed/assets/84044328/a053c3a4-6f5a-4cd9-a89d-f881649ef6ac)   |  ![Screenshot 2023-10-09 230256](https://github.com/nextcloud/spreed/assets/84044328/4e77ad55-4dcd-41aa-9bb2-ba392be0a75a) | ![Screenshot 2023-10-09 230406](https://github.com/nextcloud/spreed/assets/84044328/6ce76b6e-8184-4d5e-9fc7-f074030b305e)
 

### 🚧 Tasks

- [ ] Design/icons review
- [ ] Code review

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

2023-10-10 08:58 UTC, Antreesy commented on src/components/CallView/shared/VideoVue.vue
> +			<HideIcon fill-color="#ffffff" @click="handleClickVideo" />
```suggestion
			<HideIcon fill-color="#ffffff" />
```
Doesn't work for you like this?

2023-10-10 08:58 UTC, Antreesy commented on src/components/CallView/shared/VideoVue.vue
> +			<HideIcon fill-color="#ffffff" @click="handleClickVideo" />
IMHO it's better to replace all these 3 divs with simple classes (and maybe `::after` pseudo-elements), as they're adding only shadow or background. Can also use `background-image: var(--icon-toggle-white);` for the eye icon, although it's not crossed, as MDI component:
![image](https://github.com/nextcloud/spreed/assets/93392545/fbdc45b4-e3c9-41ab-a907-51f6d3d9af0c)

2023-10-10 08:58 UTC, Antreesy commented on src/components/CallView/CallView.vue
> +								<TransitionWrapper v-if="callParticipantModel.attributes.peerId === shownRemoteScreenPeerId && shouldShowPresenterOverlay
move to computed?

2023-10-10 08:58 UTC, Antreesy commented on src/components/CallView/CallView.vue
> +									class="presentar-overlay--collapse"
```suggestion
									class="presenter-overlay--collapse"
```

2023-10-10 08:58 UTC, Antreesy commented on src/components/CallView/CallView.vue
> +									class="presentar-overlay--collapse"
I'd also add a `title` here, as it's not clear, what button does
![image](https://github.com/nextcloud/spreed/assets/93392545/3841b206-ea7c-418a-88dc-99ba1ff305e9)

2023-10-10 08:58 UTC, Antreesy commented on src/components/CallView/CallView.vue
> +											:size="20" />
```suggestion
										<AccountBox fill-color="#ffffff" :size="20" />
```

2023-10-10 08:58 UTC, Antreesy commented on src/components/CallView/CallView.vue
> +									:key="'video-overlay-wrapper' + callParticipantModel.attributes.peerId"
maybe use `presenter-overlay-.*` for all new params?

2023-10-10 08:58 UTC, Antreesy commented on src/components/CallView/CallView.vue
> +		isStripeOpen() {
Works OK for a couple of participants, but:
- If there are more than you screen can fit, presenter may not be in the visible area
- Still a bug, when you're following participant with a screenshare and don't see his video https://github.com/nextcloud/spreed/issues/8799
![Screenshot from 2023-10-10 10-41-54](https://github.com/nextcloud/spreed/assets/93392545/98d1e507-7b28-4f77-ac5a-5a60555c63aa)

So I'd suggest to not hide a button, when stripe is open

2023-10-10 08:58 UTC, Antreesy commented on src/components/CallView/CallView.vue
> +	max-width: var(--max-width);
Not sure about px limitations: I barely see an overlay on 4K monitor. Maybe stick with 10-15vw, to always depend on screen resolution? And maybe restrict highest size to LocalVideo sizes (height: 242px)

2023-10-10 11:39 UTC, DorraJaouad commented on src/components/CallView/CallView.vue
> +	right: 8px;
We should check with designers for this as bottom-right was specified in the [design description](https://github.com/nextcloud/spreed/issues/4478#issuecomment-1691692246).

CC @jancborchardt

2023-10-12 12:35 UTC, Antreesy commented on src/components/CallView/shared/VideoVue.vue
> +			speaking: isSpeaking,
```suggestion
			speaking: isSpeaking && !isBig,
```
Agree with excluding the stripe, but Big is already promoted, so feels weird to have an outline around id

2023-10-12 12:35 UTC, Antreesy commented on src/components/CallView/shared/VideoVue.vue
> +			hover: mouseover && !unSelectable,
```suggestion
			hover: mouseover && !unSelectable  && !isBig,
```
Same here, Big is not an interactable element

2023-10-12 12:35 UTC, Antreesy commented on src/components/CallView/shared/VideoVue.vue
> +	left: 0;
nitpick: I'd move it (and border-radius) to general `.video-container::after`

2023-10-13 11:20 UTC, Antreesy approved these changes
Looks cool code-wise and running! Nothing blocking from me.
Left some minor comments for improvements, and waiting for design team for decision

2023-10-13 11:20 UTC, Antreesy commented on src/components/CallView/CallView.vue
> +			return callParticipantModel => {
Nice catch here! Small thing that could be improved:
- If video stream is receiving, but blocked on client side, we could keep this button while screen share is available (like a collapsed state for non-blocked video). And on click we just unblocking video stream and show presenter overlay

![image](https://github.com/nextcloud/spreed/assets/93392545/ee82902d-ee94-4dff-987d-428a9cfac8c7)

2023-10-13 11:20 UTC, Antreesy commented on src/components/CallView/CallView.vue
> +	right: 8px;
cc @nextcloud/designers team for input on it

2023-10-13 11:20 UTC, Antreesy commented on src/components/CallView/shared/VideoVue.vue
> +	content: '';
```suggestion
```
That will prevent ::after pseudo element from rendering, unless it's needed. You still have this rule for subclasses, so should be fine

2023-10-13 11:20 UTC, Antreesy commented on src/components/CallView/shared/VideoVue.vue
>  	border-radius: calc(var(--default-clickable-area) / 2);
Don't forget to remove it from subclass rule

2023-10-13 16:30 UTC, Antreesy commented on src/components/CallView/CallView.vue
> +			return callParticipantModel => {
Does it work fine?
Should be a method, if it includes parameters

2023-10-16 15:50 UTC, Antreesy approved these changes
Left some nitpick comments

2023-10-18 09:30 UTC, Antreesy approved these changes

2023-10-18 10:48 UTC, jancborchardt requested changes
Very cool! :) @DorraJaouad only a very small adjustment: To make the hide icon more symmetric with the one to show the video, instead of the "eye" I'd propose account-off: https://pictogrammers.com/library/mdi/icon/account-off/

2023-10-19 07:07 UTC, nickvergessen commented
So, good to merge?

2023-10-19 08:36 UTC, jancborchardt approved these changes
Looks great! :)

2023-10-19 08:42 UTC, merged