replace missing MDI icons with existing ones
nextcloud/spreed pull request #11199
Opened 2023-12-11 21:57 UTC by Antreesy

### ☑️ Resolves

- replace Lobby and GridView icons with analogs from library
- sort components

## 🖌️ UI Checklist

No visual changes. Check locked Lobby room as a guest and TopBar in a call

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences

2023-12-12 04:57 UTC, nickvergessen requested changes

2023-12-12 09:19 UTC, DorraJaouad commented on src/components/LobbyScreen.vue
> -		NcRichText,
It is just reordered

2023-12-12 09:31 UTC, DorraJaouad commented
Suggestions for icons 

CancelPresentation -> https://pictogrammers.com/library/mdi/icon/monitor-off/
CategoryMonitoring -> [pulse](https://pictogrammers.com/library/mdi/icon/pulse/) OR [clip board pulse outline](https://pictogrammers.com/library/mdi/icon/clipboard-pulse-outline/)

2023-12-12 09:39 UTC, nickvergessen commented
pulse should be fine and I guess also monitor off?

2023-12-12 15:13 UTC, Antreesy commented
Replaced PresentToAll with MonitorShare for consistency
_more monitors..._

2023-12-12 21:01 UTC, DorraJaouad approved these changes
Looks good 🖼️

2023-12-13 13:48 UTC, nickvergessen approved these changes

2023-12-13 13:57 UTC, merged