feat(TopBar): show description during call
nextcloud/spreed pull request #11428
Opened 2024-01-23 09:13 UTC by DorraJaouad

### ☑️ Resolves

* Fix #10562

I kept the same text color as we are also keeping it for the status message. There is no lighter text color other than the standard white.

## 🖌️ UI Checklist

### 🖼️ Screenshots / Screencasts

| 🏚️ Before | 🏡 After |
|------------|----------|
|![image](https://github.com/nextcloud/spreed/assets/84044328/9ee04580-71e6-4a43-8076-061feb31d9f7)      | ![image](https://github.com/nextcloud/spreed/assets/84044328/414569a8-214b-45b9-9589-09e0a436b9f8)     |

### 🚧 Tasks

- [ ] Design review

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

2024-01-23 10:03 UTC, Antreesy commented
Was introduced here: https://github.com/nextcloud/spreed/pull/8341/commits/e7f3388db737d0f93e0797a9e1961a85622de203
So I'd ask @marcoambrosini , why it has been done back then?

2024-01-23 10:14 UTC, marcoambrosini commented
> So I'd ask @marcoambrosini , why it has been done back then?

 It was done to minimize information that was not crucial during a call. Actually @jancborchardt back then you were in favor of reducing text in the call view. 
Also, as far as I can remember, no call view from other apps shows conversation or meeting description while in the call.

2024-01-23 10:16 UTC, nickvergessen approved these changes
We didn't add it because we wanted to put information like "people in call", "call duration", etc. there, but they are now in another place, so we can show the description there now.

2024-01-23 10:18 UTC, marcoambrosini commented
> We didn't add it because we wanted to put information like "people in call", "call duration", etc. 

That proposal came later on, avatar and name were there before call time was added.

2024-01-23 10:27 UTC, jancborchardt requested changes
@DorraJaouad nice! Just one thing: It looks like the text doesn’t have enough contrast, since it’s color-text-maxcontrast which is intended to be used on a light background but it’s used on dark. Either:
- Is is possible to invoke the dark-theme color-text-maxcontrast for the subline here?
- Or we use color-main-text for the subline here too, when in a call

@marcoambrosini Whatever was discussed in the past, most recent consensus was to add the description in the subline, same as how it is in the chat and as per the issue: https://github.com/nextcloud/spreed/issues/10562

2024-01-23 10:33 UTC, nickvergessen commented
> Is is possible to invoke the dark-theme color-text-maxcontrast for the subline here?

https://github.com/nextcloud/spreed/blob/c74c6f199a18aed32002a74bf36c47b98a37f49f/src/components/TopBar/TopBar.vue#L501

2024-01-23 12:53 UTC, jancborchardt commented
> > Is is possible to invoke the dark-theme color-text-maxcontrast for the subline here?
> 
> https://github.com/nextcloud/spreed/blob/c74c6f199a18aed32002a74bf36c47b98a37f49f/src/components/TopBar/TopBar.vue#L501

This is a deprecated variable though. Only text colors we should use are `color-main-text` and `color-text-maxcontrast` as per design guidelines: https://docs.nextcloud.com/server/latest/developer_manual/design/foundations.html#text-color

I'd say for simplicity and to make sure the contrast works, let's use `color-main-text` for the subline here too.

--- 

@Antreesy yes, the contrast works with dark theme enabled because the `color-text-maxcontrast` changes shade slightly. This is why I suggested: 

> Is it possible to invoke the dark-theme color-text-maxcontrast for the subline here?

2024-01-23 13:14 UTC, Antreesy commented
> This is a deprecated variable though

Then we should also migrate to `color-text-maxcontrast` in some places.
For the `color-main-text` for a description, I can't see, why not. Conversation name is bold, so would be distinguishable enough

2024-01-23 14:42 UTC, DorraJaouad commented
> let's use color-main-text for the subline here too.


It conveyed 'too much' contrast to me so I opted for the dark theme `color-text-maxcontrast`
![image](https://github.com/nextcloud/spreed/assets/84044328/eb874012-753e-4afb-9c18-a96a052fb0c0)

But I set it to `color-main-text` as suggested

2024-01-23 15:25 UTC, DorraJaouad commented on src/components/TopBar/TopBar.vue
> +					:class="{'description__in-chat' : !isInCall }">
chat : 
![image](https://github.com/nextcloud/spreed/assets/84044328/7f254dd3-77c6-4898-b94d-e8a311bbcd9b)

call:
![image](https://github.com/nextcloud/spreed/assets/84044328/01eff746-d853-4d4f-9f2a-d79e7000b783)

2024-02-05 11:10 UTC, jancborchardt approved these changes
Looks good according to screenshots, and thanks for the deprecated variable fixes! :)

2024-02-06 09:07 UTC, merged

2024-02-08 08:10 UTC, marcoambrosini commented
Can we at least go back to fading things out after some mouse inactivity?