fix(media): make an early request for userMedia to get permissions
nextcloud/spreed pull request #12128
Opened 2024-04-16 13:27 UTC by Antreesy

### ☑️ Resolves

* Fix #12122
 * initialisation is supposed to call getUserMedia in `updateAudioStream` and `updateVideoStream` separately for each device, but as it's a first attempt, we don't have a selected audioInputId or videoInputId, therefore -> early return
  * now we request permissions for both inputs at once beforehand, so don't have to wait several seconds for the second device
  * if permissions were reset at some point, and should be granted again, now media devices are selected correctly from preferences list

## 🖌️ UI Checklist

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
![image](https://github.com/nextcloud/spreed/assets/93392545/d2aed0d0-00dc-40e3-a53b-56c3d76d21be) | ![image](https://github.com/nextcloud/spreed/assets/93392545/ca621568-7324-4050-9e1f-9b34de65e8b1)

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] ⛑️ Tests are included or not possible

2024-04-16 13:28 UTC, nickvergessen commented
There was a really deep issue why we split the request to begin with, but @danxuliu should know and might be able to hint you to it.

2024-04-16 19:53 UTC, danxuliu requested changes
If both audio and video are requested both audio and video must be available. That is, the request will fail (and no permissions will be even asked for) if there is only a microphone but not a camera, or only a camera but not a microphone. A [failed `getUserMedia` throws an exception](https://github.com/nextcloud/spreed/blob/84171f71d4a94c4cb579b5b5cfd52fb69637ace2/src/utils/webrtc/MediaDevicesManager.js#L430), so the rest of the code is not executed.

Therefore, at the very least the request should be guarded with a try/catch.

Besides that, in the case of success the returned tracks should be explicitly stopped. Otherwise they might be active until a different device is explicitly selected.

Independently of that I still have not understood why requesting first the audio and then the video causes the issue :thinking: I am afraid that I will not be able to finish investigating it before tonight's RC, though... So if it fixes #12122 I guess it would be fine to merge this (once the try/catch and `stream.getTracks().forEach(track => track.stop())` is added) and if a better fix is found later we apply it for the next RC :shrug:

2024-04-18 11:17 UTC, danxuliu commented
Given that #12122 is unrelated to the latest changes, as [it is reproducible in 27-30](https://github.com/nextcloud/spreed/issues/12122#issuecomment-2061172166), I would prefer not to merge this; as a user I would prefer to give independent permissions to audio and video, rather than having to give permission to both even if I only want to use the microphone.

2024-04-18 12:00 UTC, DorraJaouad commented
> initialisation is supposed to call getUserMedia in updateAudioStream and updateVideoStream separately for each device, but as it's a first attempt, we don't have a selected audioInputId or videoInputId, therefore -> early return

This is probably the main reason why some users can't set their mic or camera. 

```
		if (videoInputId.value === null || videoInputId.value === undefined) {
			return
		}
 
```

I think this condition should be removed as devices list is needed even if the user sets "None" ( no device should be selected) or undefined (previous device was removed)

2024-04-18 13:49 UTC, nickvergessen requested changes
as per above

2024-04-18 19:12 UTC, closed without merging