fix: duplicate stun and turn servers cannot be added
nextcloud/spreed pull request #12531
Opened 2024-06-17 13:39 UTC by skalidindi53

### ☑️ Resolves

* Fix #…11852

## 🛠️ API Checklist

### 🚧 Tasks

- [x] Implemented logic to check if a TURN/STUN server is already added before adding a new one
- [x] Added a test case for checking duplicate servers

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not possible
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 🔖 Capability is added or not needed

2024-06-18 09:18 UTC, Antreesy commented
Hi, Shankar! Edited a PR info a bit:
- don't forget to put labels and assign yourself;
- same with assigning reviewers, if PR is ready;
- Milestone should be set as most recent - 💙 Next Major (30) - now, if it goes to `main` branch
- Then we're backporting it to stable branches with `/backport to stableX`, and bot does the job with assigning, labelling, and setting the milestones

2024-06-19 09:20 UTC, nickvergessen requested changes

2024-06-19 09:20 UTC, nickvergessen commented on lib/Command/Turn/Add.php
> +				$existingServer['secret'] === $secret
*Question:*
Should also error if the same server+protocol exists with a different secret?

**Must:**
Should also check the schema?

2024-06-19 09:20 UTC, nickvergessen commented on tests/php/Command/Stun/AddTest.php
> +		self::invokePrivate($this->command, 'execute', [$this->input, $this->output]);
**Must:**
```suggestion
		$this->assertSame(1, self::invokePrivate($this->command, 'execute', [$this->input, $this->output]));
```

2024-06-19 09:20 UTC, nickvergessen commented on tests/php/Command/Turn/AddTest.php
> +		self::invokePrivate($this->command, 'execute', [$this->input, $this->output]);
**Must:**
```suggestion
		$this->assertSame(1, self::invokePrivate($this->command, 'execute', [$this->input, $this->output]));
```

2024-06-19 09:20 UTC, nickvergessen commented on tests/php/Command/Turn/AddTest.php
> +	public function testAddDuplicateServer(): void {
*Nitpick:*
```suggestion

	public function testAddDuplicateServer(): void {
```

2024-06-19 09:20 UTC, nickvergessen commented on tests/php/Command/Stun/AddTest.php
> +	public function testAddDuplicateServer(): void {
*Nitpick:*
```suggestion

	public function testAddDuplicateServer(): void {
```

2024-06-19 18:11 UTC, merged