feat(RightSidebar): enforce tab navigation, show chat description in sidebar
nextcloud/spreed pull request #12846
Opened 2024-07-29 15:20 UTC by Antreesy

### ☑️ Resolves

* Ref #12800
* Follow-up of discussion in https://github.com/nextcloud/spreed/pull/12810#discussion_r1691396919

## 🖌️ UI Checklist

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
Group chat | --
![image](https://github.com/user-attachments/assets/a27d6e49-4190-4b24-b1da-f857ce6be7d1) | ![image](https://github.com/user-attachments/assets/6203fa34-9a8b-47fa-848a-d9ba275ea207)
![image](https://github.com/user-attachments/assets/240fca0e-f1a0-4a71-a7ca-4fe6cd933ba5) | ![image](https://github.com/user-attachments/assets/c2c59ab1-f0ac-4332-842a-0d924593089f)
Federated chat | --
![image](https://github.com/user-attachments/assets/1ba151f6-6691-4942-864b-2bd5d9679153) | ![image](https://github.com/user-attachments/assets/404ba10a-7daf-4f08-8f00-24eeb37475e1)
![image](https://github.com/user-attachments/assets/b2bc4225-a297-4cc8-8584-11d1ba048e39) | ![image](https://github.com/user-attachments/assets/6de41342-42fd-4137-b403-6a4143fb663e)
1-1 chat | --
![image](https://github.com/user-attachments/assets/7e3bc785-7d1c-4c11-ab42-eaceee21e8b8) | ![image](https://github.com/user-attachments/assets/7d9b6509-872d-45de-a78f-73ddf570eb01)
![image](https://github.com/user-attachments/assets/bc4f546a-93d6-42d0-b248-1a2a439ef7ab) | ![image](https://github.com/user-attachments/assets/daccc4d2-a665-4c49-89ed-9bf165bb3d81)

### 🚧 Tasks

- [x] Top bar title is cut off - keep it one line only

### 🏁 Checklist

- [x] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [x] 🖥️ Tested with Desktop client or should not be risky for it 
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

2024-07-29 15:28 UTC, ShGKme commented on src/components/TopBar/TopBar.vue
> +		padding-inline: var(--default-grid-baseline);
Maybe `2 * --default-grid-baseline`?

2024-07-29 15:28 UTC, ShGKme commented on src/components/RightSidebar/RightSidebar.vue
> +				use-extended-markdown />
Nice!

2024-07-29 15:28 UTC, ShGKme commented on src/components/RightSidebar/RightSidebar.vue
> +		force-tabs
Not sure about forced tabs... IMO, looked good without navigation when there was only on tab.

2024-07-29 16:03 UTC, nickvergessen commented on src/components/RightSidebar/RightSidebar.vue
> +			<NcRichText v-if="conversation.description"
needs a max height somehow

2024-07-30 07:39 UTC, marcoambrosini commented
@Antreesy what is the issue we're trying to solve here? At first glance I don't see improvements and only potential drawbacks

2024-07-30 07:51 UTC, Antreesy commented
@marcoambrosini check the initial PR and discussion: https://github.com/nextcloud/spreed/pull/12810#discussion_r1691396919
Was suggested either decrease the font size in TopBar to fit two lines in 34px, or find another way, like move the description out of it

2024-07-30 09:16 UTC, jancborchardt requested changes
@Antreesy I agree with @marcoambrosini that this is mostly a potential drawback – the description was intentionally moved to the subline to be always visible, which is super helpful.

We can go for a third option: Increase the height of the header bar (aka not decrease it so much) to be able to fit 2 lines of text, to also be symmetric to any of the entries in the left navigation.

2024-07-30 09:50 UTC, ShGKme commented
> We can go for a third option: Increase the height of the header bar (aka not decrease it so much) to be able to fit 2 lines of text, to also be symmetric to any of the entries in the left navigation.

@jancborchardt Then it won't be in line with the navigation toggle, navigation search, sidebar toggle, and sidebar title, which intentionally was forced to be the same everywhere in components.

2024-07-30 10:19 UTC, Antreesy commented
See https://github.com/nextcloud/spreed/pull/12851
Looks okay for me with reduced padding and default line-height (at least text won't be trimmed)

2024-07-30 11:22 UTC, marcoambrosini commented
I would downsize tue subline to 13px 
<img width="1295" alt="Screenshot 2024-07-30 at 13 13 57" src="https://github.com/user-attachments/assets/17eb3337-2ac1-4c99-a9ac-591f87e1a7b2">

We should create a new variable for it: `--font-size-small`

2024-08-01 11:35 UTC, closed without merging