feat(release): Promote Desktop, AI Summaries, Meetings and Archiving
nextcloud/spreed pull request #13898
Opened 2024-11-28 15:05 UTC by nickvergessen

![grafik](https://github.com/user-attachments/assets/cfae26ae-2e26-42be-a5a7-981691142cd5)

2024-11-28 15:13 UTC, jospoortvliet requested changes
Looking good!!!!!

2024-11-28 15:13 UTC, jospoortvliet commented on lib/Chat/Changelog/Manager.php
> +			. $this->l->t('- Desktop client for Windows, macOS and Linux is now available: %s', ['https://nextcloud.com/talk-desktop-install']) . "\n"
```suggestion
			. $this->l->t('- Introducing our desktop client for Windows, macOS and Linux: %s', ['https://nextcloud.com/talk-desktop-install']) . "\n"
```

2024-11-28 15:13 UTC, jospoortvliet commented on lib/Chat/Changelog/Manager.php
> +			. $this->l->t('- Summarize call recordings and chats with many unread messages (requires AI configuration in the server)') . "\n"
```suggestion
			. $this->l->t('- Summarize call recordings and unread messages in chats with the Nextcloud Assistant') . "\n"
```

2024-11-28 15:13 UTC, jospoortvliet commented on lib/Chat/Changelog/Manager.php
> +			. $this->l->t('- Summarize call recordings and chats with many unread messages (requires AI configuration in the server)') . "\n"
I think just naming the Assistant makes it clear enough you need that for it to work.

2024-11-28 15:22 UTC, nickvergessen commented on lib/Chat/Changelog/Manager.php
> +			. $this->l->t('- Introducing the Nextcloud Talk desktop client for Windows, macOS and Linux: %s', ['https://nextcloud.com/talk-desktop-install']) . "\n"
URL to be confirmed by @peterwebdesign

2024-11-28 16:23 UTC, AndyScherzinger approved these changes

2024-11-28 18:07 UTC, DorraJaouad approved these changes
LGTM

2024-11-29 08:55 UTC, nickvergessen commented
Redirect is in place (linking to the wrong anchor, but we can merge already, so translators can translate over the weekend)

2024-11-29 08:55 UTC, merged

2024-11-29 11:12 UTC, nickvergessen commented
/backport to stable30