fix(signaling): add UI warning in call with 4+ participants
nextcloud/spreed pull request #14022
Opened 2024-12-18 15:07 UTC by Antreesy

### ☑️ Resolves

* Ref #14018

## 🖌️ UI Checklist

### 🖼️ Screenshots / Screencasts

🏚️ Before | 🏡 After
-- | --
Screenshot before | Screenshot after

<img width="744" alt="image" src="https://github.com/user-attachments/assets/9264cd66-9e57-4a51-99ee-da35ee75ddc2" />

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [ ] 🌏 Tested with different browsers / clients:
  - [ ] Chromium (Chrome / Edge / Opera / Brave)
  - [ ] Firefox
  - [ ] Safari
  - [ ] Talk Desktop
  - [ ] Not risky to browser differences / client
- [ ] 🖌️ Design was reviewed, approved or inspired by the design team
- [ ] ⛑️ Tests are included or not possible
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required

2024-12-18 17:22 UTC, nickvergessen reviewed
Just a quick comment, two things:
- the warning basically will be shown in any non 2 person call in the future
- we had this warning or a similar one in the past, can you check and find it or find where it got lost?

2024-12-18 17:22 UTC, nickvergessen commented on src/App.vue
> +			if (this.$store.getters.isModerator || this.$store.getters.participantsList(token)?.length > 4) {
```suggestion
			if (this.$store.getters.participantsList(token)?.length > 2) {
```

2024-12-18 18:19 UTC, Antreesy commented
> we had this warning or a similar one in the past, can you check and find it or find where it got lost?

Never appeared after migration to Vue in 2019: https://github.com/nextcloud/spreed/commit/88d7d7820e5ae8f4a3d897605124ad7755926494

2024-12-19 11:03 UTC, jancborchardt requested changes
The issue with the toast is that it gets clicked away and is not permanent enough. I would suggest to put a yellow NcNoteCard on the top of the right sidebar (or left navigation, although that seems to be less relevant if this only shows in a call) that shows throughout the duration of the call.

And it also needs to provide how to fix it – if shown to users, needs to say something actionable like "Contact your admin for further assistance"

2024-12-19 12:56 UTC, nickvergessen commented
If a sidebar it should be right, as left is folded away when starting a call.
Could also see an icon on the call view similarly to the connection warning?

2025-01-07 11:24 UTC, nickvergessen commented on src/App.vue
> +				showWarning(t('spreed', 'Having a call with more than 4 participants without external signaling server can cause connectivity issues and cause high load on participating devices'))
Instead of showWarning we should use a NcNoteCard in the header of the right sidebar below the Conversation name (above the lobby and other quick settings). Together with an actionable "Learn more" link which links to https://portal.nextcloud.com/article/Nextcloud-Talk/High-Performance-Backend/Installation-of-Nextcloud-Talk-High-Performance-Backend for now.

2025-01-08 11:39 UTC, nickvergessen approved these changes
Good for me.

We can also add it to the call view additionally as described by Jan, or we wait to see how the current version resonates.

2025-01-08 12:36 UTC, merged