Use new app settings components
nextcloud/spreed pull request #4195
Opened 2020-09-22 11:25 UTC by ma12-co

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

2020-09-22 11:46 UTC, nickvergessen commented on src/components/SettingsDialog/SettingsDialog.vue
> +		<AppSettingsSection :title="t('spreed', 'keyboard shortcuts')">
```suggestion
		<AppSettingsSection :title="t('spreed', 'Keyboard shortcuts')">
```

2020-10-19 10:45 UTC, danxuliu requested changes
This error appears now in the browser console when opening the main Talk UI (even if the settings dialog is not opened):
```
[Vue warn]: Error in updated hook: "TypeError: this.$el.querySelector is not a function"

found in

---> <AppSettingsDialog>
       <SettingsDialog> at src/components/SettingsDialog/SettingsDialog.vue
         <Content>
           <App> at src/App.vue
             <Root>
```

Additionally, clicking on the headers in the left area causes the right area to scroll to the appropriate section, but scrolling in the right area does not change the highlighted header in the left area (although this may be an issue of the component from nextcloud-vue, I do not know).

I have also noticed that [content in the right area can not be selected using the mouse](https://github.com/nextcloud/nextcloud-vue/issues/1505) (not that I want to, but I found it strange :-P ) and, [in Firefox, it is not possible to scroll in the right area](https://github.com/nextcloud/nextcloud-vue/issues/1506) using the arrow keys (although it works in Chromium). ~~However it also happened before using the new AppSettings components, so it could be a problem with the Modal component (just a guess).~~ Opened issues in `nextcloud-vue`.

2020-10-27 08:45 UTC, PVince81 commented
Missing padding on top:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/277525/97277442-c65ab280-1838-11eb-9e52-711254d7c3d8.png">

2020-10-28 16:41 UTC, PVince81 commented
seems this was closed by mistake

2020-11-02 16:41 UTC, PVince81 commented
please note that nextcloud-vue was updated, so many stuff that wasn't working before is working now.
you might need to rebase

2020-11-03 17:23 UTC, ma12-co commented
Ready for review!

2020-11-05 11:27 UTC, PVince81 commented
a wild conflict appears!

2020-11-11 15:56 UTC, ma12-co commented
Rebased!!

2020-11-12 08:13 UTC, nickvergessen approved these changes

2020-11-12 08:19 UTC, merged