Message status ux improvements
nextcloud/spreed pull request #4741
Opened 2020-12-10 16:14 UTC by ma12-co

Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

2020-12-11 10:42 UTC, nickvergessen commented
![Peek 2020-12-11 11-41](https://user-images.githubusercontent.com/213943/101894063-e4d8fb00-3ba5-11eb-9396-84762db8e4a5.gif)

Something weird is going on

2020-12-14 10:27 UTC, PVince81 commented
Looks fine in regular mode visually.

However with the Dyslexia font the timestamp wraps, and it messes up with the mouseenter/mouseleave event so the hover is broken. See the video above.

2020-12-14 10:29 UTC, PVince81 requested changes
See comments

2020-12-14 10:29 UTC, PVince81 commented on src/components/MessagesList/MessagesGroup/Message/Message.vue
> +	width: 44px;
I think you can use $clickable-area here

2020-12-16 16:58 UTC, ma12-co commented
> However with the Dyslexia font the timestamp wraps, and it messes up with the mouseenter/mouseleave event so the hover is broken. See the video above.

I tried to reproduce but I'm unable to make it wrap

2020-12-16 17:05 UTC, nickvergessen commented
English US locale so you have 11:50 AM (need 4 digits + 2 letters)

2020-12-16 17:31 UTC, ma12-co commented
Updated the layout so that now the date, however long, never wraps.

![Screenshot from 2020-12-16 18-28-06](https://user-images.githubusercontent.com/26852655/102384302-dab36400-3fcc-11eb-8a58-dcda9235866a.png)

2020-12-17 07:16 UTC, PVince81 reviewed
I guess this wasn't ready for re-review yet. Let us know when it is

2020-12-17 07:16 UTC, PVince81 commented on src/components/MessagesList/MessagesGroup/Message/Message.vue
> +	.date {
```
ERROR in 
src/components/MessagesList/MessagesGroup/Message/Message.vue
 499:2  ✖  Expected indentation of 2 tabs   indentation
 500:3  ✖  Expected indentation of 3 tabs   indentation
```

2020-12-17 07:16 UTC, PVince81 commented on src/components/MessagesList/MessagesGroup/Message/Message.vue
> +				<span v-if="hasDate" v-tooltip.auto="messageDate" class="date">{{ 'looongdateee' }}</span>
some leftover from testing ?

2020-12-17 08:08 UTC, ma12-co commented
> I guess this wasn't ready for re-review yet. Let us know when it is


Uff, sorry.. I amended my commit without first saving the last changes :facepalm: : ...Ready for review now

2020-12-17 09:15 UTC, nickvergessen commented
Messages of others look out of place, I'm Alice:
![Bildschirmfoto von 2020-12-17 10-13-50](https://user-images.githubusercontent.com/213943/102467513-abded180-4050-11eb-8021-b75db56b6b59.png)

2020-12-17 12:22 UTC, nickvergessen approved these changes

2020-12-17 12:24 UTC, merged