Unify stun and turn server urls
nextcloud/spreed pull request #5582
Opened 2021-05-06 19:52 UTC by danxuliu

Requires #5491 and #5503

This is a breaking change for Talk 12.

The format resembles the `RTCIceServer` format, so the returned values can be directly used by the WebUI like done until now. Mobile clients will need to be adjusted, though.

**Important:** The [RTCIceServer MDN page](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer) states that `Avoid specifying an unnecessarily large number of URLs in the urls property; the startup time for your connection will go up substantially. Every server in the list will be contacted and tried out before one is selected to be used for negotiation.` It should be verified whether that applies too when using trickle ICE or not; if it does then it might be needed to rethink the format before merging this.

### Before

```
stunservers: [
  [
    url: "stunServer1"
  ],
  [
    url: "stunServer2"
  ],
  [
    url: "stunServer3"
  ]
],
turnservers: [
  [
    url: [ "turnServer1-1" ],
    urls: [ "turnServer1-1" ],
    username: "user1"
    credentials: "credentials1"
  ],
  [
    url: [ "turnServer1-2" ],
    urls: [ "turnServer1-2" ],
    username: "user1"
    credentials: "credentials1"
  ],
  [
    url: [ "turnServer2" ],
    url: [ "turnServer2" ],
    username: "user2"
    credentials: "credentials2"
  ],
]
```

### After

```
stunservers: [
  [
    urls: [ "stunServer1", "stunServer2", "stunServer3" ]
  ],
],
turnservers: [
  [
    urls: [ "turnServer1-1", "turnServer1-2" ],
    username: "user1"
    credentials: "credentials1"
  ],
  [
    url: [ "turnServer2" ],
    username: "user2"
    credentials: "credentials2"
  ],
]
```

2021-05-07 06:08 UTC, nickvergessen commented on lib/Controller/SignalingController.php
> +			'urls' => $stunUrls
Can you bump the api version for signaling and create different arrays based on the already available `$apiVersion`?

2021-05-11 23:08 UTC, danxuliu commented
Rebased on master and bumped API version instead of modifying the previous one.

Tested with Firefox and Chromium; it should work with Safari too... but tests are welcome ;-)

2021-05-14 14:57 UTC, Ivansss commented
Could we add the capability "signaling-v3" here? :)

2021-05-14 17:14 UTC, nickvergessen commented
Yes we should add that capability and at the same time (as said in the other PR) we can drop v1+v2 at the same time as all clients for nextcloud22 need to be updated for conversation-v4 already and there is no fallback possible.

2021-05-17 07:50 UTC, danxuliu commented
But if v1+v2 are dropped (I guess by [replacing `v(1|2|3)` with `v3` in _routes.php_](https://github.com/nextcloud/spreed/pull/5582/files#diff-6301937af1cc1575e9e18ecd27c4a51f0d3cf9ce12e59a14709f626dfa3ef952R65)) then there is no need to have different arrays, or there is? :thinking:

2021-05-17 08:28 UTC, nickvergessen commented
Exactly that was the plan? Make everything simple as you don't need to support the other things.

2021-05-17 12:01 UTC, danxuliu commented
But then what did you mean by [`create different arrays based on the already available $apiVersion?`](https://github.com/nextcloud/spreed/pull/5582#discussion_r627952091)?

2021-05-17 16:01 UTC, nickvergessen commented
Hmm maybe too many context switches 🤔

2021-05-18 17:17 UTC, danxuliu commented
> Hmm maybe too many context switches :thinking:

Try setting event loops :-P

Capability added and previous endpoint versions dropped.

2021-05-19 07:53 UTC, nickvergessen approved these changes

2021-05-19 08:00 UTC, nickvergessen requested changes
please update all signaling urls to v3

2021-05-19 08:07 UTC, nickvergessen approved these changes
Fixed with a fixup commit

2021-05-19 13:28 UTC, nickvergessen commented
Rebased after #5465  and did the fixups

2021-05-19 16:38 UTC, danxuliu commented
Fixed a bug with the `stunservers` array (it was an object rather than an array, I had fixed it already but it seems that I failed to push :facepalm:), moved dropping all the endpoints to the third commit rather than the second one, and removed some unneeded code now that the previous versions are not supported.

2021-05-20 07:26 UTC, merged