Read unread icons
nextcloud/spreed pull request #5893
Opened 2021-06-29 00:59 UTC by Pytal

Closes #5892

![image](https://user-images.githubusercontent.com/24800714/123721135-81a97000-d83a-11eb-9c2b-95735545ad6a.png)

![image](https://user-images.githubusercontent.com/24800714/123721141-840bca00-d83a-11eb-990b-6298df1a7487.png)

2021-06-29 06:26 UTC, skjnldsv approved these changes

2021-06-29 07:02 UTC, PVince81 commented on src/components/LeftSidebar/ConversationsList/Conversation.vue
> +				icon="icon-checkmark"
use a material design icon here as well ?

2021-06-29 07:02 UTC, nickvergessen commented on src/components/MessagesList/MessagesGroup/Message/Message.vue
> +									<CheckCircleOutline size="20" />
```suggestion
									<CheckCircleOutline
										decorative
										title=""
										:size="16" />
```

Not a too big fan of the icon, but I guess it clarifies the action and better than no icon

2021-06-29 08:39 UTC, marcoambrosini requested changes
I don't the unread icon is appropriate, what about `eye-off-outline`?

![eye-off-outline](https://user-images.githubusercontent.com/26852655/123765684-40f73880-d8c6-11eb-829b-f3aad51a66e9.png)

2021-06-30 07:10 UTC, nickvergessen commented
Moved both to material icons and using outline eye now:

Mark read | Mark unread
---|---
![Bildschirmfoto von 2021-06-30 09-07-38](https://user-images.githubusercontent.com/213943/123917366-fe476600-d982-11eb-919b-a99e9dce6696.png) | ![Bildschirmfoto von 2021-06-30 09-07-34](https://user-images.githubusercontent.com/213943/123917373-ff789300-d982-11eb-8a32-ac16d2cb45b5.png)

2021-06-30 07:11 UTC, nickvergessen commented
/backport to stable22

2021-06-30 07:27 UTC, marcoambrosini approved these changes

2021-06-30 07:43 UTC, merged