Add a counter for the direct mentions
nextcloud/spreed pull request #6193
Opened 2021-09-01 15:57 UTC by nickvergessen

This allows the UI can show the user bubble depending on user vs. all mentions

Backend for #4623

- [x] Expose whether there are personal mentions
- [x] Update the counter when a user was mentioned directly
- [ ] Add docs
- [ ] Add unit tests
- [ ] Add integration tests

2021-09-02 06:37 UTC, nickvergessen commented
Since we can not reset the counter partly when the readmarker is changed, I will convert the API result to a boolean

2021-09-16 09:02 UTC, nickvergessen commented
Ready for review

2021-09-20 09:48 UTC, danxuliu requested changes
The direct mention counter is reset when the last mention is read, so it is not properly reset if the last direct mention is read but there is another not direct mention after it.

I have added an integration test that shows it.

2021-09-20 10:03 UTC, nickvergessen commented
We don't have that data available `¯\_(ツ)_/¯`
To fix that we would need to retain a second real id. But I guess we could so that too.
Not sure why I didn't do it like that from the beginning

2021-09-20 10:58 UTC, nickvergessen commented
Fixed

2021-09-20 12:43 UTC, danxuliu reviewed
Should the database field (and thus the attribute in the model) be named `last_mention_direct_message` rather than `last_mention_direct` for consistency with `last_mention_message`?

Other than that, :+1:

2021-09-20 12:48 UTC, nickvergessen commented
Would be `last_direct_mention_message` but I find this getting too long and unreadable (and already coming very close to the oracle size limit)

2021-09-20 13:17 UTC, merged