Refactor notifier method
nextcloud/spreed pull request #6675
Opened 2021-12-08 10:57 UTC by vitormattos

2021-12-10 16:15 UTC, vitormattos commented
I identified that after the refactor reduced a bit the quantity of queries on this flow.

2021-12-13 09:01 UTC, nickvergessen requested changes

2021-12-13 10:34 UTC, vitormattos commented on lib/Chat/Notifier.php
> +		if (count($list) === count($usersToNotify)) {
If I do this change the all will be stay on array and the method getActorsByType will do a query using all as a username and all will be returned by the method. The All isn't a user to notify.

2021-12-13 10:36 UTC, vitormattos commented on lib/Chat/Notifier.php
> +		return $mentionedUsers;
Not, because I included the type on array.

2021-12-13 11:14 UTC, vitormattos commented on lib/Chat/Notifier.php
> +		return $mentionedUsers;
Will be necessary array_filter and array_map using two interactions on the array. Using foreach I only used one interaction.

2021-12-13 11:15 UTC, vitormattos commented on lib/Chat/Notifier.php
> +		return $mentionedUsers;
The type returned on mention array have the type on singular, I used this step to use the right type used on Talk.

2021-12-13 11:30 UTC, vitormattos commented on lib/Chat/Notifier.php
> +			return $user['id'] !== 'all';
The objective isn't check if `@all` exists, the objective is remove `@all`

2022-01-20 12:47 UTC, nickvergessen approved these changes

2022-01-20 12:47 UTC, merged