Define if job is time sensitive
nextcloud/spreed pull request #6913
Opened 2022-02-17 17:30 UTC by vitormattos

Close #6874

| Job                          | interval | status           | detail                                                |
| ---------------------------- | -------- | ---------------- | ----------------------------------------------------- |
| CheckHostedSignalingServer   | 1 hour   | TIME_INSENSITIVE | Check the status of hosted signalign servers          |
| CheckMatterbridges           | 15 min   | TIME_INSENSITIVE | Kill zombie bridges                                   |
| CheckReferenceIdColumn       | 1 hour   | TIME_INSENSITIVE | Check if column reference_id exists on comment table. |
| ExpireSignalingMessage       | 5 min    | TIME_INSENSITIVE | Expire signaling message                              |
| RemoveEmptyRooms             | 5 min    | TIME_INSENSITIVE | Remove empty rooms                                    |
| ResetAssignedSignalingServer | 5 min    | TIME_INSENSITIVE | Unassign empty rooms from signalign server            |
| RetryJob                     | ?        | null             | Not timed job                                         |

2022-02-17 17:56 UTC, nickvergessen commented on lib/BackgroundJob/ExpireSignalingMessage.php
> +		$this->setTimeSensitivity(IJob::TIME_INSENSITIVE);
Not a real usecase as I think instances that need the maintenance feature also need an HPB, but:
```suggestion
		$this->setTimeSensitivity(IJob::TIME_SENSITIVE);
```

2022-02-17 17:58 UTC, nickvergessen commented on lib/BackgroundJob/RemoveEmptyRooms.php
>  		$this->setInterval(60 * 5);
then we can also lift this to 24h, as it will only run in the nights anyway.

2022-02-17 17:58 UTC, nickvergessen commented on lib/BackgroundJob/ResetAssignedSignalingServer.php
> +		$this->setTimeSensitivity(IJob::TIME_INSENSITIVE);
```suggestion
		$this->setTimeSensitivity(IJob::TIME_SENSITIVE);
```
This needs to execute often

2022-02-18 11:46 UTC, vitormattos commented
Sorry the misunderstanding about the constant.
I swapped the understanding.
I fixed now.

2022-02-22 15:22 UTC, nickvergessen requested changes
See comment

2022-02-22 16:16 UTC, nickvergessen approved these changes

2022-02-23 09:24 UTC, merged