Add changelog for 11.3.6, 12.2.4 and 13.0.4
nextcloud/spreed pull request #7001
Opened 2022-03-15 08:15 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2022-03-15 08:16 UTC, nickvergessen commented on CHANGELOG.md
> +  [#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX](https://github.com/nextcloud/spreed/pull/XXX)
Backport of https://github.com/nextcloud/spreed/pull/6993

2022-03-17 13:14 UTC, danxuliu requested changes

2022-03-17 13:14 UTC, danxuliu commented on CHANGELOG.md
> +  [#6919](https://github.com/nextcloud/spreed/pull/6919)
Duplicated PR number.

2022-03-17 13:18 UTC, nickvergessen commented on CHANGELOG.md
> +  [#6919](https://github.com/nextcloud/spreed/pull/6919)
Fixed

2022-03-17 13:19 UTC, danxuliu approved these changes

2022-03-17 13:24 UTC, merged