🔕 Silent send messages front-end
nextcloud/spreed pull request #7392
Opened 2022-05-19 13:18 UTC by marcoambrosini

Fix #7366

2022-05-30 10:12 UTC, marcoambrosini commented
removed the TS changes from here for now since it's harder than I thought, so that this can go through

2022-05-30 10:46 UTC, nickvergessen commented on src/store/messagesStore.js
>  	 */
```suggestion
	 * @param {object} context default store context;
	 * @param {object} data Passed in parameters
	 * @param {object} data.temporaryMessage temporary message, must already have been added to messages list.
	 * @param {object} data.options post request options.
	 */
```

2022-06-01 08:58 UTC, nickvergessen requested changes

2022-06-01 08:58 UTC, nickvergessen commented on src/store/messagesStore.js
> +	 * @param {object} context default store context;
Duplicate @param "context"

2022-06-01 08:58 UTC, nickvergessen commented on src/components/NewMessageForm/NewMessageForm.vue
> +							{{ t('spreed', 'The recipients won\'t be notifyed about this message') }}
```suggestion
							{{ t('spreed', 'The recipients won\'t be notified about this message') }}
```

Also maybe we put this in a computed and for one to one chats we then use:
```suggestion
							{{ t('spreed', 'The recipient won\'t be notified about this message') }}
```

Other than that should it be "participants?

2022-06-01 13:02 UTC, nickvergessen approved these changes

2022-06-01 13:18 UTC, merged