Improve spacing left sidebar
nextcloud/spreed pull request #8027
Opened 2022-09-27 13:41 UTC by CarlSchwan

Remove too much padding in the conversation list and add spacing between entries. Now everything is padding and gap is 4px.

After:

![image](https://user-images.githubusercontent.com/23653902/192542664-243ede3e-6c91-4302-84d3-b8f31cdab40c.png)

2022-09-27 14:01 UTC, nickvergessen requested changes
This is being tracked and discussed in https://github.com/nextcloud/nextcloud-vue/issues/3287

So blocking merge for now.

2022-09-27 14:34 UTC, jancborchardt commented on src/components/LeftSidebar/ConversationsList/ConversationsList.vue
> +	gap: 4px;
Variables here please :)
```suggestion
	gap: var(--default-grid-baseline, 4px);
```

2022-09-27 14:34 UTC, jancborchardt requested changes
Looks good but see comment :)

2022-09-29 16:28 UTC, nickvergessen commented
Replaced by #8037 + vue lib update

2022-09-29 16:28 UTC, closed without merging