Add app config to specify default attachment folder location
nextcloud/spreed pull request #8465
Opened 2022-12-13 16:41 UTC by tcitworld

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

2022-12-13 18:35 UTC, vitormattos submitted a review, later dismissed
All app config need to be added to file https://github.com/nextcloud/spreed/blob/master/docs/settings.md

2022-12-20 09:29 UTC, nickvergessen commented
@tcitworld want to finish this? Or should Vitor take over?

2022-12-20 10:02 UTC, tcitworld commented
I'm not sure I'll get some time before end of the vacation, so please take over if you have time to finish this!

2023-01-04 19:37 UTC, nickvergessen requested changes

2023-01-04 19:37 UTC, nickvergessen commented on docs/settings.md
> +| `attachment_folder`   | `config => attachments => folder` | Value of app setting `default_attachment_folder` | Path owned by the user to store uploads and received shares. It is created if it does
Value of app config ...

2023-01-04 19:37 UTC, nickvergessen commented on docs/settings.md
> +| `default_attachment_folder`          | string                                                           | `\Talk`    |        | Specify default attachment folder location
Please sort by type, so after `bridge_bot_password`

2023-01-04 19:37 UTC, nickvergessen commented on docs/settings.md
> +| `default_attachment_folder`          | string                                                           | `\Talk`    |        | Specify default attachment folder location
Also we use unix paths not windows...
```suggestion
| `default_attachment_folder`          | string                                                           | `/Talk`    |        | Specify default attachment folder location                                                                                                                                        |
```

2023-01-04 19:46 UTC, nickvergessen approved these changes

2023-01-04 21:44 UTC, tcitworld reviewed
Can't approve, but ✅

2023-01-05 01:44 UTC, merged