Update documentation and expose room property
nextcloud/spreed pull request #8471
Opened 2022-12-16 15:03 UTC by vitormattos

Ref: #8326

### 🚧 TODO

- [x] `callStartTime`
  - [x] is not documented in https://github.com/nextcloud/spreed/blob/master/docs/conversation.md
  - [x] was missed to be added to the single room request (which is used by the HPB) https://github.com/nextcloud/spreed/blob/527ad87a78c3e18e9797681c076379e0c3bbe79e/lib/Controller/RoomController.php#L452-L472
- [x] `callRecording`
  - [x] is not exposed in the RoomController
    - [x] Also then needs documenting in https://github.com/nextcloud/spreed/blob/master/docs/conversation.md

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

2022-12-19 19:27 UTC, nickvergessen requested changes

2022-12-19 19:27 UTC, nickvergessen commented on docs/conversation.md
> +| `callRecording`         | int     | v4    |         | Call recording status
```suggestion
| `callStartTime`         | int     | v4    |         | Timestamp when the call was started (only available with `recording-v1` capability)                                                                                                                                                                                                                                                                                                               |
| `callRecording`         | int     | v4    |         | Type of call recording (see [Constants - Call recording status](constants.md#call-recording-status)) (only available with `recording-v1` capability)                                                                                                                                                                                                                                                                                                                                                                        |
```

2022-12-19 19:27 UTC, nickvergessen commented on lib/Controller/RoomController.php
> +			'callRecording' => 0,
```suggestion
			'callRecording' => Room::RECORDING_NONE,
```

2022-12-21 16:11 UTC, marcoambrosini approved these changes

2022-12-21 17:33 UTC, nickvergessen approved these changes

2022-12-21 17:33 UTC, merged