Fix channel name autocomplete
nextcloud/spreed pull request #8482
Opened 2022-12-21 12:41 UTC by st3iny

Fix #8480

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [ ] 🔖 Capability is added or not needed

2022-12-21 13:45 UTC, vitormattos requested changes
Will be good cover this case on unit tests:
https://github.com/nextcloud/spreed/blob/master/tests/php/Chat/ChatManagerTest.php#L664-L684

2022-12-21 13:50 UTC, nickvergessen commented
@vitormattos please take over.

2022-12-29 23:59 UTC, nickvergessen commented on tests/php/Chat/ChatManagerTest.php
> +			'case sensitive, not found A in here' => [
```suggestion
			'case sensitive, not found H in here' => [
```

2023-01-02 06:09 UTC, nickvergessen approved these changes

2023-01-02 06:10 UTC, merged

2023-01-02 06:10 UTC, nickvergessen commented
/backport to stable25

2023-01-02 06:10 UTC, nickvergessen commented
/backport to stable24