Correct MessageButtonsBar position (related to message itself) on screen
nextcloud/spreed pull request #8716
Opened 2023-02-07 16:26 UTC by Antreesy

Signed-off-by: Maksim Sukharev <antreesy.web@gmail.com>

Fix #8463

### 🖼️ Screenshots

🏡 After
One- and two-line text messages:
![image](https://user-images.githubusercontent.com/93392545/217301520-110e74f9-1fa7-40fc-9866-4e9d79ba0a37.png)
Three- and more:
![image](https://user-images.githubusercontent.com/93392545/217302027-ea69bb08-4ca0-4d78-81de-25716358af31.png)
Deleted messages:
![image](https://user-images.githubusercontent.com/93392545/217302245-56aa860f-a322-4aaf-b412-f080081ba829.png)
In case there is not enough space to fit buttons bar under the message info:
![image](https://user-images.githubusercontent.com/93392545/217302491-82884eb0-bc5b-4300-a9b2-a24146552bcc.png)

### 🚧 TODO

- [ ] Visual check
- [ ] Code-review

### 🏁 Checklist

- [X] 📘 API documentation in `docs/` has been updated or is not required
- [X] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [X] 🔖 Capability is added or not needed

2023-02-08 19:56 UTC, nickvergessen approved these changes
Seems to work, not a fan of z-index thou

2023-02-08 19:56 UTC, nickvergessen commented on src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
> +	z-index: 1;
🙈

2023-02-09 14:15 UTC, marcoambrosini requested changes
I'm not a fan of the fact that the bar changes position that much depending on the messages heights. Could we put this on hold and think of a better solution in a few days?

2023-02-17 10:32 UTC, ShGKme commented on src/components/MessagesList/MessagesGroup/Message/Message.vue
> +			}
The solution based on `this.$parent.$parent.$el` in a Vue component depends on other components' implementation in a very implicit way. Maybe we can achieve it in a more explicit solution?

2023-02-17 10:32 UTC, ShGKme commented on src/components/MessagesList/MessagesGroup/Message/Message.vue
> +			}
Also, "36" feels like a magic number here to me. If I understand correctly, it is calculated from the current value of the `$clickable-area` SASS variable. Still, it doesn't depend on the variable value (changing the SASS variable value would require updating this value in the code). If it is equal to the `.message-buttons-bar` bottom property, could we get the element's current value? Or the `--default-clickable-area` CSS variable if it is the same thing.

2023-02-21 14:14 UTC, marcoambrosini approved these changes

2023-02-21 14:15 UTC, merged