Make recording files visible in the specific section Media tab of the…
nextcloud/spreed pull request #8798
Opened 2023-02-20 12:29 UTC by vitormattos

### 🚧 TODO

- close #8663

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [ ] 🔖 Capability is added or not needed

2023-02-20 14:23 UTC, nickvergessen requested changes

2023-02-20 14:23 UTC, nickvergessen commented on lib/Model/Attachment.php
> +	public const TYPE_RECORD_AUDIO = 'record-audio';
Needs to be documented in https://github.com/nextcloud/spreed/blob/062ed28540c21d09a19cf7077033e1b0165658c4/docs/constants.md#shared-item-types

2023-02-20 14:24 UTC, nickvergessen commented
I'm actually unsure if it should be 2 sections or one, but then again with the different types it might be better in split sections?
cc @marcoambrosini

2023-02-20 14:25 UTC, nickvergessen commented
PS screenshot in https://github.com/nextcloud/spreed/pull/8800

2023-02-23 12:37 UTC, vitormattos commented
Updated the web client implementation here: #8800 
I unified the sections only on the client side.

2023-02-23 13:18 UTC, nickvergessen commented
> I unified the sections only on the client side.

That's not good enough, as it needs more coordination with mobile clients, breaks the pagination, etc.

2023-02-23 13:40 UTC, nickvergessen approved these changes

2023-02-23 16:03 UTC, merged