Adding caption to the uploaded media [web draft]
nextcloud/spreed pull request #8949
Opened 2023-03-03 11:55 UTC by Antreesy

For #5354 

### 🖼️ Screenshots

🏚️ Below media | 🏡 Above media
---|---
![Screenshot from 2023-03-03 12-18-34](https://user-images.githubusercontent.com/93392545/222713272-c2713bae-b525-4d77-a831-49541729d5c4.png) | ![Screenshot from 2023-03-03 12-31-26](https://user-images.githubusercontent.com/93392545/222713289-f43a98ae-2bd9-4928-a5b6-8cd25d7e9ed1.png)

### 🚧 TODO

- [ ] Add handling metadata `{mediaCaption: string}` on backend
- [ ] Reproduce on Android
- [ ] Reproduce on iOS

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [ ] 🔖 Capability is added or not needed

2023-03-03 12:01 UTC, nickvergessen requested changes

2023-03-03 12:01 UTC, nickvergessen commented on src/components/UploadEditor.vue
> +				<input v-model="mediaCaption">
Should use NcContentEditable aka the NewMessageForm similar to 
https://github.com/nextcloud/spreed/blob/master/src/components/BreakoutRoomsEditor/SendMessageDialog.vue#L28

2023-08-24 15:25 UTC, jancborchardt reviewed
Looks super nice generally! Some feedback:
- [ ] In the modal, the "Send" button is now not primary anymore, would be cool if the "Paper plane" icon button would be a primary button icon+text
- [x] Currently when composing, the images are above the text, but when sending the text comes first. In other messengers, when you send a message with a picture, usually the picture is above the text too.
- [ ] Sort of related to the previous point, maybe it would be good to put the photos next to each other or tile them somehow else when there are multiple ones. Otherwise the text and photos are very far apart and the message also takes a lot of space if you send a message with 10 pictures

2024-01-19 20:41 UTC, Antreesy commented
Rebased onto master, dropped all irrelevant/outdated/conflicted code

2026-08-04 07:46 UTC, closed without merging