Allow to receive messages without marking notifications as unread
nextcloud/spreed pull request #9066
Opened 2023-03-15 16:54 UTC by SystemKeeper

Currently when retrieving new messages, notifications of the spreed app are marked as read by default:
https://github.com/nextcloud/spreed/blob/049c56f4d85cd35bbba5079061cce0f0f9fda513/lib/Chat/ChatManager.php#L606-L608
This is usually fine, but when we want to retrieve messages in the background on the mobile clients (to have the messages ready when we open the app again).
This PR adds a new parameter `markNotificationsAsRead` which allows to explicitly state that we do not want to mark notifications as read when retrieving messages.

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

2023-03-15 19:32 UTC, nickvergessen requested changes

2023-03-15 19:32 UTC, nickvergessen commented on docs/chat.md
> +| `markNotificationsAsRead` | int  | `0` to not mark notifications as read (Default: `1`, only available with `chat-read-status` capability
```suggestion
| `markNotificationsAsRead` | int  | `0` to not mark notifications as read (Default: `1`, only available with `chat-read-status` capability)                                                                                                                                                        |
```

2023-03-16 10:59 UTC, vitormattos requested changes

2023-03-16 10:59 UTC, vitormattos commented on lib/Capabilities.php
> +				'chat-keep-notifications'
Using a comma at the last element of array every when is indented, when add another row don't will touch the previous row.

By example, you didn't touch any row, only added a new row. This is a good point when we need to use `git blame`.
```suggestion
				'chat-keep-notifications',
```

2023-03-16 11:45 UTC, SystemKeeper commented
Both comments addressed, rebased and squashed

2023-03-16 14:08 UTC, vitormattos approved these changes

2023-03-16 23:10 UTC, merged

2023-03-21 12:00 UTC, nickvergessen commented on docs/chat.md
> +| `markNotificationsAsRead` | int  | `0` to not mark notifications as read (Default: `1`, only available with `chat-read-status` capability)
Should be `chat-keep-notifications` ?