feat(avatar): Use the first emoji of room names as avatar emoji
nextcloud/spreed pull request #9424
Opened 2023-05-02 14:29 UTC by nickvergessen

### ☑️ Resolves

* Fix #8444 

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
![image](https://user-images.githubusercontent.com/213943/235696814-c54c8b16-8e39-4e7c-ba5c-b7aac1dcad6a.png) | ![Bildschirmfoto vom 2023-05-02 16-23-58](https://user-images.githubusercontent.com/213943/235696730-75b69724-720a-44c4-abc9-24dd0b8f961a.png)

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

2023-05-02 14:45 UTC, jancborchardt approved these changes
Looks suuuper cool! :) :sparkles:

2023-05-02 14:49 UTC, marcoambrosini approved these changes

2023-05-02 14:49 UTC, marcoambrosini commented on lib/Service/AvatarService.php
> +			<text x="50%" y="350" style="font-weight:normal;font-size:280px;font-family:{font};text-anchor:middle;fill:#{fgFill}">{letter}</text>
```suggestion
			<text x="50%" y="350" style="font-weight:normal;font-size:240px;font-family:{font};text-anchor:middle;fill:#{fgFill}">{letter}</text>
```

Very nice, though some emojis almost touch the boundaries of the avatar circle. I would slightly scale them and give them some air.

2023-05-02 15:05 UTC, vitormattos requested changes

2023-05-02 15:31 UTC, nickvergessen commented on lib/Service/AvatarService.php
> +		</svg>';
That actually generates an error, as there is content before the XML start, etc. so let's stick with the current version.

2023-05-02 15:46 UTC, vitormattos approved these changes

2023-05-02 17:14 UTC, vitormattos commented
After merge this PR will be necessary rebase #9423 with this changes and make possible to change the avatar when change the conversation name.

2023-05-02 18:41 UTC, SystemKeeper commented
> > when the conversation name is changed, the emoji is not updated:
> 
> It's only the browser caching the image for 24h

Can’t we just get the md5 of the emoji?

2023-05-02 20:34 UTC, merged

2023-05-03 15:36 UTC, ShGKme commented
> Can’t we just get the md5 of the emoji?

Do you mean, to calculate `md5` for each conversation everywhere?

2023-05-03 15:42 UTC, SystemKeeper commented
> Do you mean, to calculate `md5` for each conversation everywhere?

For cache busting we need a way to identify if an avatar changed. For default avatars the md5 of the filename is used, for custom avatars I think the hash is already at the filename or something, and for emojis this is added at https://github.com/nextcloud/spreed/pull/9423/files#diff-a7e5eb4728a4ad105af312d21ceb1bd6dd7a70068ba67d4b1881099dcae1076bR289-R291