Add user setting for toggle typing privacy
nextcloud/spreed pull request #9455
Opened 2023-05-04 17:06 UTC by vitormattos

API side of #9248 to implement an user setting to toggle typing privacy

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not required
- [x] 📘 API documentation in `docs/` has been updated or is not required
- [x] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [x] 🔖 Capability is added or not needed

2023-05-04 17:08 UTC, nickvergessen commented on lib/Config.php
> +	public function getTypingPrivacy(string $userId): int {
```suggestion
	public function getUserTypingPrivacy(string $userId): int {
```

2023-05-04 17:11 UTC, nickvergessen requested changes
* Missing from the list in https://github.com/nextcloud/spreed/blob/70e25dc91c16f1f95a58237848020a0f74166772/docs/settings.md#L27
* Missing in https://github.com/nextcloud/spreed/blob/5ac5d00e2d64f580aadc3257d166c1df4c904313/lib/Controller/SettingsController.php

Please also search if the preference name, capability name or config function is used anywhere else

2023-05-04 22:08 UTC, nickvergessen requested changes

2023-05-04 22:08 UTC, nickvergessen commented on docs/constants.md
> +* `1` Hide the typing status
```suggestion
* `0` Typing status is public
* `1` Typing status is private
```

2023-05-04 22:08 UTC, nickvergessen commented on lib/Controller/AvatarController.php
https://github.com/nextcloud/spreed/pull/9459

2023-05-04 22:08 UTC, nickvergessen commented on lib/Controller/SettingsController.php
>  		if ($setting === 'read_status_privacy') {
```suggestion
		if ($setting === 'typing_privacy' || $setting === 'read_status_privacy') {
```

2023-05-04 22:08 UTC, nickvergessen commented on lib/TInitialState.php
> +			'0'
```suggestion
			Participant::PRIVACY_PUBLIC
```

2023-05-04 22:08 UTC, nickvergessen commented on tests/integration/features/chat-2/typing-privacy.feature
> +    # Hide
```suggestion
    # Private
```

2023-05-04 22:08 UTC, nickvergessen commented on tests/integration/features/chat-2/typing-privacy.feature
> +    # Visible
```suggestion
    # Public
```

2023-05-05 11:08 UTC, nickvergessen approved these changes

2023-05-05 11:46 UTC, SystemKeeper commented
Fine by me.
CC: @danxuliu About the capability name, so you're aware

2023-05-05 11:47 UTC, merged