Fix media settings in files sidebar
nextcloud/spreed pull request #9792
Opened 2023-06-16 05:54 UTC by marcoambrosini

When starting a call from the files sidebar and while editing a file, the media settings was not display because it was covered by the file dialog. Increasing the z-index of the media settings dialog didn't fix the issue (it's unclear to me why not). Removing the container of the media settings dialog and thereby assigning the default body as container fixes the issue.

### ☑️ Resolves

* Fix #8709 

### 🖼️ Screenshots

<img width="822" alt="Screenshot 2023-06-16 at 13 45 12" src="https://github.com/nextcloud/spreed/assets/26852655/303b7673-692e-47c8-a4a6-888b0a225413">

2023-06-16 06:59 UTC, Antreesy requested changes
As expected, it breaks opening media settings on fullscreen

2023-06-16 08:45 UTC, marcoambrosini commented
Hmmm nice catch. Why is it that in Files the media settings are visible even in fullscreen mode while in talk they're not?

2023-06-16 09:27 UTC, ShGKme commented
> Hmmm nice catch. Why is it that in Files the media settings are visible even in fullscreen mode while in talk they're not?

As far as I know, in Files there is no real "Fullscreen mode". Only open Viewer and Fullscreen "styles" for the Sidebar.

In Talk the Fullscreen mode is a "real" fullscreen with native [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) for the Talk app (`div#content-vue`) element. Only Talk is "fullscreen-ed", you see no header and ect. In this mode, Talk app is a [top layer](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer) element. No element outside the Talk (`div#content-vue`) can be above, no matter what z-index it has.

That was the reason, why Daniel created the `uiMode` store here: https://github.com/nextcloud/spreed/pull/6119

We need some huge rework here in general. I'm working on it as a part of https://github.com/nextcloud/spreed/issues/9626

2023-07-18 20:19 UTC, rriemann commented
I have already notified this to our Nextcloud sales engineer. It is so important for our use to have this fixed. Please make it happen for the next update. :pray:

2023-07-18 21:51 UTC, Antreesy commented
Just a thought: maybe we could try to replace mainContainer for the sidebars? For the main view of Talk app it's obvious to have block like #content-talk, but for Files all and others we should also cover the whole screen:

https://github.com/nextcloud/spreed/blob/master/src/mainFilesSidebar.js#L72

2023-12-19 09:24 UTC, closed without merging