Final step of conversation creation doesn't focus
nextcloud/spreed pull request #9910
Opened 2023-07-07 14:51 UTC by DorraJaouad

### ☑️ Resolves

* Fix #7584
It is the best solution I found so far but should be improved. 

Some workarounds I tried:

- in Confirmation mounted()
this.$nextTick().then() and double $nextTick() were not sufficient to mount the content

- in NewGroupConversation component watch()
this.$nextTick().then() and double $nextTick() didn't work here as well.

### 🚧 Tasks

- [ ] Alternative solution
- [ ] Code review

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not required
- [ ] 📘 API documentation in `docs/` has been updated or is not required
- [ ] 📗 User documentation in https://github.com/nextcloud/documentation/tree/master/user_manual/talk has been updated or is not required
- [ ] 🔖 Capability is added or not needed

2023-07-07 16:05 UTC, Antreesy requested changes
Actually, `<Confirmation />` component is a pile of props and boilerplate, without complex logic.
If we get rid of it and move the code to the `<NewGroupConversation />`, it will be just 30 lines of template + 3 lines of script + 15 lines of styles.

And that could allow us to access buttons directly, and watch after `success` and `error` - if they are truthy, we'll focus an appropriate button

2023-07-07 16:06 UTC, Antreesy commented on src/components/LeftSidebar/NewGroupConversation/Confirmation/Confirmation.vue
> +	},
And don't forget to lint files, you have a semicolon

2023-07-11 06:46 UTC, Antreesy approved these changes
Tested on web, and works so far!
Let's add one more button in focus, and squash commits into one (or two)

2023-07-11 06:46 UTC, Antreesy commented on src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
> +				<div v-else-if="page === 2" class="confirmation new-group-conversation__content">
```suggestion
				<div v-else-if="page === 2" class="new-group-conversation__content">
```

We could omit that class, as it doesn't have any styles applied

2023-07-11 06:46 UTC, Antreesy commented on src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
> +		success(value) {
Let's also add the same, but watch for `error` and focus `Close` button instead, as it'll be only available

2023-07-11 10:38 UTC, DorraJaouad commented
/backport to stable27

2023-07-11 10:38 UTC, DorraJaouad commented
/backport to stable26

2023-07-11 21:14 UTC, merged

2023-07-19 11:45 UTC, nickvergessen commented
27 Backport is in #9954 
26 is canceled, so removing the label